apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app-svc
spec:
  selector:
    app: my-k8s-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

